CREATE TABLE workspace_onboarding_profiles (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL UNIQUE,
    primary_use_case VARCHAR(64) NOT NULL,
    work_style VARCHAR(64) NOT NULL,
    activation_status VARCHAR(32) NOT NULL,
    activation_note VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE workspace_subscriptions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL UNIQUE,
    plan_code VARCHAR(32) NOT NULL,
    plan_label VARCHAR(64) NOT NULL,
    subscription_status VARCHAR(32) NOT NULL,
    billing_interval VARCHAR(32) NOT NULL,
    included_credits INT NOT NULL,
    extra_credits INT NOT NULL,
    renews_at DATE,
    commercial_note VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO workspace_onboarding_profiles (
    workspace_id,
    primary_use_case,
    work_style,
    activation_status,
    activation_note
)
SELECT
    w.id,
    'operations',
    'small_team',
    'ready',
    'Workspace pronto para iniciar tarefas, projetos e busca operacional.'
FROM workspaces w;

INSERT INTO workspace_subscriptions (
    workspace_id,
    plan_code,
    plan_label,
    subscription_status,
    billing_interval,
    included_credits,
    extra_credits,
    renews_at,
    commercial_note
)
SELECT
    w.id,
    'starter',
    'Starter',
    'active',
    'monthly',
    500,
    0,
    CURRENT_DATE + 30,
    'Base comercial inicial do workspace. Billing externo e overage entram em uma trilha posterior.'
FROM workspaces w;
