CREATE TABLE workspace_usage_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    event_type VARCHAR(64) NOT NULL,
    resource_type VARCHAR(64),
    resource_id VARCHAR(128),
    actor_user_id BIGINT,
    details VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_workspace_usage_events_workspace_created
    ON workspace_usage_events (workspace_id, created_at DESC);

CREATE TABLE workspace_credit_ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    entry_type VARCHAR(32) NOT NULL,
    source_type VARCHAR(64) NOT NULL,
    source_id VARCHAR(128),
    credits_delta INT NOT NULL,
    balance_after INT,
    note VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_workspace_credit_ledger_workspace_created
    ON workspace_credit_ledger_entries (workspace_id, created_at DESC);

CREATE TABLE workspace_cost_ledger_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT,
    provider_code VARCHAR(64) NOT NULL,
    model_code VARCHAR(128),
    capability VARCHAR(64) NOT NULL,
    request_id VARCHAR(128),
    status VARCHAR(32) NOT NULL,
    estimated_input_tokens INT,
    estimated_output_tokens INT,
    estimated_cost_usd DOUBLE PRECISION,
    latency_ms BIGINT,
    fallback_used BOOLEAN NOT NULL DEFAULT FALSE,
    routing_mode VARCHAR(32),
    policy_decision_summary VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_workspace_cost_ledger_workspace_created
    ON workspace_cost_ledger_entries (workspace_id, created_at DESC);

CREATE INDEX idx_workspace_cost_ledger_provider_created
    ON workspace_cost_ledger_entries (provider_code, created_at DESC);

CREATE TABLE workspace_invoices (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    invoice_number VARCHAR(64) NOT NULL UNIQUE,
    status VARCHAR(32) NOT NULL,
    amount_brl NUMERIC(12, 2) NOT NULL,
    currency VARCHAR(8) NOT NULL DEFAULT 'BRL',
    due_at DATE,
    paid_at TIMESTAMP,
    description VARCHAR(255),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_workspace_invoices_workspace_created
    ON workspace_invoices (workspace_id, created_at DESC);

CREATE TABLE workspace_payment_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workspace_id BIGINT NOT NULL,
    invoice_id BIGINT,
    gateway_event_id VARCHAR(128),
    event_type VARCHAR(64) NOT NULL,
    status VARCHAR(32) NOT NULL,
    amount_brl NUMERIC(12, 2),
    payload_hash VARCHAR(128),
    occurred_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    processed_at TIMESTAMP,
    CONSTRAINT fk_workspace_payment_events_invoice
        FOREIGN KEY (invoice_id) REFERENCES workspace_invoices(id)
);

CREATE INDEX idx_workspace_payment_events_workspace_occurred
    ON workspace_payment_events (workspace_id, occurred_at DESC);

INSERT INTO workspace_credit_ledger_entries (
    workspace_id,
    entry_type,
    source_type,
    source_id,
    credits_delta,
    balance_after,
    note
)
SELECT
    ws.workspace_id,
    'grant',
    'subscription_snapshot',
    CONCAT('workspace:', ws.workspace_id),
    (ws.included_credits + ws.extra_credits),
    (ws.included_credits + ws.extra_credits),
    'Snapshot inicial de creditos a partir da assinatura existente.'
FROM workspace_subscriptions ws
WHERE NOT EXISTS (
    SELECT 1
    FROM workspace_credit_ledger_entries ledger
    WHERE ledger.workspace_id = ws.workspace_id
);
