package com.lume.workspace.inference;

public enum InferenceProtocol {
    OPENAI_RESPONSES,
    OPENAI_CHAT_COMPLETIONS,
    ANTHROPIC_MESSAGES,
    GEMINI_GENERATE_CONTENT,
    COHERE_CHAT_V2,
    BEDROCK_CONVERSE,
    CLOUDFLARE_OPENAI_COMPAT,
    CUSTOM_RESEARCH,
    CUSTOM_THREAT_INTEL,
    UNSUPPORTED
}
